# Generated by Django 5.0.14 on 2026-02-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelog',
            name='latitude_in',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timelog',
            name='latitude_out',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timelog',
            name='longitude_in',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timelog',
            name='longitude_out',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
